// Code generated by MockGen. DO NOT EDIT.
// Source: grpc/cassandra/nodetool/v1/nodetool.pb.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
)
